export interface IPokedexType {
  galarID: number;
  name: string;
  nationalID: number;
  types: [string, string?];
}

const galarPokedex: IPokedexType[] = [
  {
    galarID: 1,
    name: "Grookey",
    nationalID: 810,
    types: ["Grass"],
  },
  {
    galarID: 2,
    name: "Thwackey",
    nationalID: 811,
    types: ["Grass"],
  },
  {
    galarID: 3,
    name: "Rillaboom",
    nationalID: 812,
    types: ["Grass"],
  },
  {
    galarID: 4,
    name: "Scorbunny",
    nationalID: 813,
    types: ["Fire"],
  },
  {
    galarID: 5,
    name: "Raboot",
    nationalID: 814,
    types: ["Fire"],
  },
  {
    galarID: 6,
    name: "Cinderace",
    nationalID: 815,
    types: ["Fire"],
  },
  {
    galarID: 7,
    name: "Sobble",
    nationalID: 816,
    types: ["Water"],
  },
  {
    galarID: 8,
    name: "Drizzile",
    nationalID: 817,
    types: ["Water"],
  },
  {
    galarID: 9,
    name: "Inteleon",
    nationalID: 818,
    types: ["Water"],
  },
  {
    galarID: 10,
    name: "Blipbug",
    nationalID: 824,
    types: ["Bug"],
  },
  {
    galarID: 11,
    name: "Dottler",
    nationalID: 825,
    types: ["Bug", "Psychic"],
  },
  {
    galarID: 12,
    name: "Orbeetle",
    nationalID: 826,
    types: ["Bug", "Psychic"],
  },
  {
    galarID: 13,
    name: "Caterpie",
    nationalID: 10,
    types: ["Bug"],
  },
  {
    galarID: 14,
    name: "Metapod",
    nationalID: 11,
    types: ["Bug"],
  },
  {
    galarID: 15,
    name: "Butterfree",
    nationalID: 12,
    types: ["Bug", "Flying"],
  },
  {
    galarID: 16,
    name: "Grubbin",
    nationalID: 736,
    types: ["Bug"],
  },
  {
    galarID: 17,
    name: "Charjabug",
    nationalID: 737,
    types: ["Bug", "Electric"],
  },
  {
    galarID: 18,
    name: "Vikavolt",
    nationalID: 738,
    types: ["Bug", "Electric"],
  },
  {
    galarID: 19,
    name: "Hoothoot",
    nationalID: 163,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 20,
    name: "Noctowl",
    nationalID: 164,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 21,
    name: "Rookidee",
    nationalID: 821,
    types: ["Flying"],
  },
  {
    galarID: 22,
    name: "Corvisquire",
    nationalID: 822,
    types: ["Flying"],
  },
  {
    galarID: 23,
    name: "Corviknight",
    nationalID: 823,
    types: ["Flying", "Steel"],
  },
  {
    galarID: 24,
    name: "Skwovet",
    nationalID: 819,
    types: ["Normal"],
  },
  {
    galarID: 25,
    name: "Greedent",
    nationalID: 820,
    types: ["Normal"],
  },
  {
    galarID: 26,
    name: "Pidove",
    nationalID: 519,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 27,
    name: "Tranquill",
    nationalID: 520,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 28,
    name: "Unfezant",
    nationalID: 521,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 29,
    name: "Nickit",
    nationalID: 827,
    types: ["Dark"],
  },
  {
    galarID: 30,
    name: "Thievul",
    nationalID: 828,
    types: ["Dark"],
  },
  {
    galarID: 31,
    name: "Zigzagoon",
    nationalID: 263,
    types: ["Dark", "Normal"],
  },
  {
    galarID: 32,
    name: "Linoone",
    nationalID: 264,
    types: ["Dark", "Normal"],
  },
  {
    galarID: 33,
    name: "Obstagoon",
    nationalID: 862,
    types: ["Dark", "Normal"],
  },
  {
    galarID: 34,
    name: "Wooloo",
    nationalID: 831,
    types: ["Normal"],
  },
  {
    galarID: 35,
    name: "Dubwool",
    nationalID: 832,
    types: ["Normal"],
  },
  {
    galarID: 36,
    name: "Lotad",
    nationalID: 270,
    types: ["Water", "Grass"],
  },
  {
    galarID: 37,
    name: "Lombre",
    nationalID: 271,
    types: ["Water", "Grass"],
  },
  {
    galarID: 38,
    name: "Ludicolo",
    nationalID: 272,
    types: ["Water", "Grass"],
  },
  {
    galarID: 39,
    name: "Seedot",
    nationalID: 273,
    types: ["Grass"],
  },
  {
    galarID: 40,
    name: "Nuzleaf",
    nationalID: 274,
    types: ["Grass", "Dark"],
  },
  {
    galarID: 41,
    name: "Shiftry",
    nationalID: 275,
    types: ["Grass", "Dark"],
  },
  {
    galarID: 42,
    name: "Chewtle",
    nationalID: 833,
    types: ["Water"],
  },
  {
    galarID: 43,
    name: "Drednaw",
    nationalID: 834,
    types: ["Water", "Rock"],
  },
  {
    galarID: 44,
    name: "Purrloin",
    nationalID: 509,
    types: ["Dark"],
  },
  {
    galarID: 45,
    name: "Liepard",
    nationalID: 510,
    types: ["Dark"],
  },
  {
    galarID: 46,
    name: "Yamper",
    nationalID: 835,
    types: ["Electric"],
  },
  {
    galarID: 47,
    name: "Boltund",
    nationalID: 836,
    types: ["Electric"],
  },
  {
    galarID: 48,
    name: "Bunnelby",
    nationalID: 659,
    types: ["Normal"],
  },
  {
    galarID: 49,
    name: "Diggersby",
    nationalID: 660,
    types: ["Normal", "Ground"],
  },
  {
    galarID: 50,
    name: "Minccino",
    nationalID: 572,
    types: ["Normal"],
  },
  {
    galarID: 51,
    name: "Cinccino",
    nationalID: 573,
    types: ["Normal"],
  },
  {
    galarID: 52,
    name: "Bounsweet",
    nationalID: 761,
    types: ["Grass"],
  },
  {
    galarID: 53,
    name: "Steenee",
    nationalID: 762,
    types: ["Grass"],
  },
  {
    galarID: 54,
    name: "Tsareena",
    nationalID: 763,
    types: ["Grass"],
  },
  {
    galarID: 55,
    name: "Oddish",
    nationalID: 43,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 56,
    name: "Gloom",
    nationalID: 44,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 57,
    name: "Vileplume",
    nationalID: 45,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 58,
    name: "Bellossom",
    nationalID: 182,
    types: ["Grass"],
  },
  {
    galarID: 59,
    name: "Budew",
    nationalID: 406,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 60,
    name: "Roselia",
    nationalID: 315,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 61,
    name: "Roserade",
    nationalID: 407,
    types: ["Grass", "Poison"],
  },
  {
    galarID: 62,
    name: "Wingull",
    nationalID: 278,
    types: ["Water", "Flying"],
  },
  {
    galarID: 63,
    name: "Pelipper",
    nationalID: 279,
    types: ["Water", "Flying"],
  },
  {
    galarID: 64,
    name: "Joltik",
    nationalID: 595,
    types: ["Bug", "Electric"],
  },
  {
    galarID: 65,
    name: "Galvantula",
    nationalID: 596,
    types: ["Bug", "Electric"],
  },
  {
    galarID: 66,
    name: "Electrike",
    nationalID: 309,
    types: ["Electric"],
  },
  {
    galarID: 67,
    name: "Manectric",
    nationalID: 310,
    types: ["Electric"],
  },
  {
    galarID: 68,
    name: "Vulpix",
    nationalID: 37,
    types: ["Fire"],
  },
  {
    galarID: 69,
    name: "Ninetales",
    nationalID: 38,
    types: ["Fire"],
  },
  {
    galarID: 70,
    name: "Growlithe",
    nationalID: 58,
    types: ["Fire"],
  },
  {
    galarID: 71,
    name: "Arcanine",
    nationalID: 59,
    types: ["Fire"],
  },
  {
    galarID: 72,
    name: "Vanillite",
    nationalID: 582,
    types: ["Ice"],
  },
  {
    galarID: 73,
    name: "Vanillish",
    nationalID: 583,
    types: ["Ice"],
  },
  {
    galarID: 74,
    name: "Vanilluxe",
    nationalID: 584,
    types: ["Ice"],
  },
  {
    galarID: 75,
    name: "Swinub",
    nationalID: 220,
    types: ["Ice", "Ground"],
  },
  {
    galarID: 76,
    name: "Piloswine",
    nationalID: 221,
    types: ["Ice", "Ground"],
  },
  {
    galarID: 77,
    name: "Mamoswine",
    nationalID: 473,
    types: ["Ice", "Ground"],
  },
  {
    galarID: 78,
    name: "Delibird",
    nationalID: 225,
    types: ["Ice", "Flying"],
  },
  {
    galarID: 79,
    name: "Snorunt",
    nationalID: 361,
    types: ["Ice"],
  },
  {
    galarID: 80,
    name: "Glalie",
    nationalID: 362,
    types: ["Ice"],
  },
  {
    galarID: 81,
    name: "Froslass",
    nationalID: 478,
    types: ["Ice", "Ghost"],
  },
  {
    galarID: 82,
    name: "Baltoy",
    nationalID: 343,
    types: ["Ground", "Psychic"],
  },
  {
    galarID: 83,
    name: "Claydol",
    nationalID: 344,
    types: ["Ground", "Psychic"],
  },
  {
    galarID: 84,
    name: "Mudbray",
    nationalID: 749,
    types: ["Ground"],
  },
  {
    galarID: 85,
    name: "Mudsdale",
    nationalID: 750,
    types: ["Ground"],
  },
  {
    galarID: 86,
    name: "Dwebble",
    nationalID: 557,
    types: ["Bug", "Rock"],
  },
  {
    galarID: 87,
    name: "Crustle",
    nationalID: 558,
    types: ["Bug", "Rock"],
  },
  {
    galarID: 88,
    name: "Golett",
    nationalID: 622,
    types: ["Ground", "Ghost"],
  },
  {
    galarID: 89,
    name: "Golurk",
    nationalID: 623,
    types: ["Ground", "Ghost"],
  },
  {
    galarID: 90,
    name: "Munna",
    nationalID: 517,
    types: ["Psychic"],
  },
  {
    galarID: 91,
    name: "Musharna",
    nationalID: 518,
    types: ["Psychic"],
  },
  {
    galarID: 92,
    name: "Natu",
    nationalID: 177,
    types: ["Psychic", "Flying"],
  },
  {
    galarID: 93,
    name: "Xatu",
    nationalID: 178,
    types: ["Psychic", "Flying"],
  },
  {
    galarID: 94,
    name: "Stufful",
    nationalID: 759,
    types: ["Normal", "Fighting"],
  },
  {
    galarID: 95,
    name: "Bewear",
    nationalID: 760,
    types: ["Normal", "Fighting"],
  },
  {
    galarID: 96,
    name: "Snover",
    nationalID: 459,
    types: ["Grass", "Ice"],
  },
  {
    galarID: 97,
    name: "Abomasnow",
    nationalID: 460,
    types: ["Grass", "Ice"],
  },
  {
    galarID: 98,
    name: "Krabby",
    nationalID: 98,
    types: ["Water"],
  },
  {
    galarID: 99,
    name: "Kingler",
    nationalID: 99,
    types: ["Water"],
  },
  {
    galarID: 100,
    name: "Wooper",
    nationalID: 194,
    types: ["Water", "Ground"],
  },
  {
    galarID: 101,
    name: "Quagsire",
    nationalID: 195,
    types: [undefined],
  },
  {
    galarID: 102,
    name: "Corphish",
    nationalID: 341,
    types: ["Water"],
  },
  {
    galarID: 103,
    name: "Crawdaunt",
    nationalID: 342,
    types: ["Water", "Dark"],
  },
  {
    galarID: 104,
    name: "Nincada",
    nationalID: 290,
    types: ["Bug", "Ground"],
  },
  {
    galarID: 105,
    name: "Ninjask",
    nationalID: 291,
    types: ["Bug", "Flying"],
  },
  {
    galarID: 106,
    name: "Shedinja",
    nationalID: 292,
    types: ["Bug", "Ghost"],
  },
  {
    galarID: 107,
    name: "Tyrogue",
    nationalID: 236,
    types: ["Fighting"],
  },
  {
    galarID: 108,
    name: "Hitmonlee",
    nationalID: 106,
    types: ["Fighting"],
  },
  {
    galarID: 109,
    name: "Hitmonchan",
    nationalID: 107,
    types: ["Fighting"],
  },
  {
    galarID: 110,
    name: "Hitmontop",
    nationalID: 237,
    types: ["Fighting"],
  },
  {
    galarID: 111,
    name: "Pancham",
    nationalID: 674,
    types: ["Fighting"],
  },
  {
    galarID: 112,
    name: "Pangoro",
    nationalID: 675,
    types: ["Fighting", "Dark"],
  },
  {
    galarID: 113,
    name: "Klink",
    nationalID: 599,
    types: ["Steel"],
  },
  {
    galarID: 114,
    name: "Klang",
    nationalID: 600,
    types: ["Steel"],
  },
  {
    galarID: 115,
    name: "Klinklang",
    nationalID: 601,
    types: ["Steel"],
  },
  {
    galarID: 116,
    name: "Combee",
    nationalID: 415,
    types: ["Bug", "Flying"],
  },
  {
    galarID: 117,
    name: "Vespiquen",
    nationalID: 416,
    types: ["Bug", "Flying"],
  },
  {
    galarID: 118,
    name: "Bronzor",
    nationalID: 436,
    types: ["Steel", "Psychic"],
  },
  {
    galarID: 119,
    name: "Bronzong",
    nationalID: 437,
    types: ["Steel", "Psychic"],
  },
  {
    galarID: 120,
    name: "Ralts",
    nationalID: 280,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 121,
    name: "Kirlia",
    nationalID: 281,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 122,
    name: "Gardevoir",
    nationalID: 282,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 123,
    name: "Gallade",
    nationalID: 475,
    types: ["Psychic", "Fighting"],
  },
  {
    galarID: 124,
    name: "Drifloon",
    nationalID: 425,
    types: ["Ghost", "Flying"],
  },
  {
    galarID: 125,
    name: "Drifblim",
    nationalID: 426,
    types: ["Ghost", "Flying"],
  },
  {
    galarID: 126,
    name: "Gossifleur",
    nationalID: 829,
    types: ["Grass"],
  },
  {
    galarID: 127,
    name: "Eldegoss",
    nationalID: 830,
    types: ["Grass"],
  },
  {
    galarID: 128,
    name: "Cherubi",
    nationalID: 420,
    types: ["Grass"],
  },
  {
    galarID: 129,
    name: "Cherrim",
    nationalID: 421,
    types: ["Grass"],
  },
  {
    galarID: 130,
    name: "Stunky",
    nationalID: 434,
    types: ["Poison", "Dark"],
  },
  {
    galarID: 131,
    name: "Skuntank",
    nationalID: 435,
    types: ["Poison", "Dark"],
  },
  {
    galarID: 132,
    name: "Tympole",
    nationalID: 535,
    types: ["Water"],
  },
  {
    galarID: 133,
    name: "Palpitoad",
    nationalID: 536,
    types: ["Water", "Ground"],
  },
  {
    galarID: 134,
    name: "Seismitoad",
    nationalID: 537,
    types: ["Water", "Ground"],
  },
  {
    galarID: 135,
    name: "Duskull",
    nationalID: 355,
    types: ["Ghost"],
  },
  {
    galarID: 136,
    name: "Dusclops",
    nationalID: 356,
    types: ["Ghost"],
  },
  {
    galarID: 137,
    name: "Dusknoir",
    nationalID: 477,
    types: ["Ghost"],
  },
  {
    galarID: 138,
    name: "Machop",
    nationalID: 66,
    types: ["Fighting"],
  },
  {
    galarID: 139,
    name: "Machoke",
    nationalID: 67,
    types: ["Fighting"],
  },
  {
    galarID: 140,
    name: "Machamp",
    nationalID: 68,
    types: ["Fighting"],
  },
  {
    galarID: 141,
    name: "Gastly",
    nationalID: 92,
    types: ["Ghost", "Poison"],
  },
  {
    galarID: 142,
    name: "Haunter",
    nationalID: 93,
    types: ["Ghost", "Poison"],
  },
  {
    galarID: 143,
    name: "Gengar",
    nationalID: 94,
    types: ["Ghost", "Poison"],
  },
  {
    galarID: 144,
    name: "Magikarp",
    nationalID: 129,
    types: ["Water"],
  },
  {
    galarID: 145,
    name: "Gyarados",
    nationalID: 130,
    types: ["Water", "Flying"],
  },
  {
    galarID: 146,
    name: "Goldeen",
    nationalID: 118,
    types: ["Water"],
  },
  {
    galarID: 147,
    name: "Seaking",
    nationalID: 119,
    types: ["Water"],
  },
  {
    galarID: 148,
    name: "Remoraid",
    nationalID: 223,
    types: ["Water"],
  },
  {
    galarID: 149,
    name: "Octillery",
    nationalID: 224,
    types: ["Water"],
  },
  {
    galarID: 150,
    name: "Shellder",
    nationalID: 90,
    types: ["Water"],
  },
  {
    galarID: 151,
    name: "Cloyster",
    nationalID: 91,
    types: ["Water", "Ice"],
  },
  {
    galarID: 152,
    name: "Feebas",
    nationalID: 349,
    types: ["Water"],
  },
  {
    galarID: 153,
    name: "Milotic",
    nationalID: 350,
    types: ["Water"],
  },
  {
    galarID: 154,
    name: "Basculin",
    nationalID: 550,
    types: ["Water"],
  },
  {
    galarID: 155,
    name: "Wishiwashi",
    nationalID: 746,
    types: ["Water"],
  },
  {
    galarID: 156,
    name: "Pyukumuku",
    nationalID: 771,
    types: ["Water"],
  },
  {
    galarID: 157,
    name: "Trubbish",
    nationalID: 568,
    types: ["Poison"],
  },
  {
    galarID: 158,
    name: "Garbodor",
    nationalID: 569,
    types: ["Poison"],
  },
  {
    galarID: 159,
    name: "Sizzlipede",
    nationalID: 850,
    types: ["Fire", "Bug"],
  },
  {
    galarID: 160,
    name: "Centiskorch",
    nationalID: 851,
    types: ["Fire", "Bug"],
  },
  {
    galarID: 161,
    name: "Rolycoly",
    nationalID: 837,
    types: ["Rock"],
  },
  {
    galarID: 162,
    name: "Carkol",
    nationalID: 838,
    types: ["Rock", "Fire"],
  },
  {
    galarID: 163,
    name: "Coalossal",
    nationalID: 839,
    types: ["Rock", "Fire"],
  },
  {
    galarID: 164,
    name: "Diglett",
    nationalID: 50,
    types: ["Ground"],
  },
  {
    galarID: 165,
    name: "Dugtrio",
    nationalID: 51,
    types: ["Ground"],
  },
  {
    galarID: 166,
    name: "Drilbur",
    nationalID: 529,
    types: ["Ground"],
  },
  {
    galarID: 167,
    name: "Excadrill",
    nationalID: 530,
    types: ["Ground", "Steel"],
  },
  {
    galarID: 168,
    name: "Roggenrola",
    nationalID: 524,
    types: ["Rock"],
  },
  {
    galarID: 169,
    name: "Boldore",
    nationalID: 525,
    types: ["Rock"],
  },
  {
    galarID: 170,
    name: "Gigalith",
    nationalID: 526,
    types: ["Rock"],
  },
  {
    galarID: 171,
    name: "Timburr",
    nationalID: 532,
    types: ["Fighting"],
  },
  {
    galarID: 172,
    name: "Gurdurr",
    nationalID: 533,
    types: ["Fighting"],
  },
  {
    galarID: 173,
    name: "Conkeldurr",
    nationalID: 534,
    types: ["Fighting"],
  },
  {
    galarID: 174,
    name: "Woobat",
    nationalID: 527,
    types: ["Psychic", "Flying"],
  },
  {
    galarID: 175,
    name: "Swoobat",
    nationalID: 528,
    types: ["Psychic", "Flying"],
  },
  {
    galarID: 176,
    name: "Noibat",
    nationalID: 714,
    types: ["Flying", "Dragon"],
  },
  {
    galarID: 177,
    name: "Noivern",
    nationalID: 715,
    types: ["Flying", "Dragon"],
  },
  {
    galarID: 178,
    name: "Onix",
    nationalID: 95,
    types: ["Rock", "Ground"],
  },
  {
    galarID: 179,
    name: "Steelix",
    nationalID: 208,
    types: ["Steel", "Ground"],
  },
  {
    galarID: 180,
    name: "Arrokuda",
    nationalID: 846,
    types: ["Water"],
  },
  {
    galarID: 181,
    name: "Barraskewda",
    nationalID: 847,
    types: ["Water"],
  },
  {
    galarID: 182,
    name: "Meowth",
    nationalID: 52,
    types: ["Steel"],
  },
  {
    galarID: 183,
    name: "Perrserker",
    nationalID: 863,
    types: ["Steel"],
  },
  {
    galarID: 184,
    name: "Persian",
    nationalID: 53,
    types: ["Normal"],
  },
  {
    galarID: 185,
    name: "Milcery",
    nationalID: 868,
    types: ["Fairy"],
  },
  {
    galarID: 186,
    name: "Alcremie",
    nationalID: 869,
    types: ["Fairy"],
  },
  {
    galarID: 187,
    name: "Cutiefly",
    nationalID: 742,
    types: ["Bug", "Fairy"],
  },
  {
    galarID: 188,
    name: "Ribombee",
    nationalID: 743,
    types: ["Bug", "Fairy"],
  },
  {
    galarID: 189,
    name: "Ferroseed",
    nationalID: 597,
    types: ["Grass", "Steel"],
  },
  {
    galarID: 190,
    name: "Ferrothorn",
    nationalID: 598,
    types: ["Grass", "Steel"],
  },
  {
    galarID: 191,
    name: "Pumpkaboo",
    nationalID: 710,
    types: ["Ghost", "Grass"],
  },
  {
    galarID: 192,
    name: "Gourgeist",
    nationalID: 711,
    types: ["Ghost", "Grass"],
  },
  {
    galarID: 193,
    name: "Pichu",
    nationalID: 172,
    types: ["Electric"],
  },
  {
    galarID: 194,
    name: "Pikachu",
    nationalID: 25,
    types: ["Electric"],
  },
  {
    galarID: 195,
    name: "Raichu",
    nationalID: 26,
    types: ["Electric"],
  },
  {
    galarID: 196,
    name: "Eevee",
    nationalID: 133,
    types: ["Normal"],
  },
  {
    galarID: 197,
    name: "Vaporeon",
    nationalID: 134,
    types: ["Water"],
  },
  {
    galarID: 198,
    name: "Jolteon",
    nationalID: 135,
    types: ["Electric"],
  },
  {
    galarID: 199,
    name: "Flareon",
    nationalID: 136,
    types: ["Fire"],
  },
  {
    galarID: 200,
    name: "Espeon",
    nationalID: 196,
    types: ["Psychic"],
  },
  {
    galarID: 201,
    name: "Umbreon",
    nationalID: 197,
    types: ["Dark"],
  },
  {
    galarID: 202,
    name: "Leafeon",
    nationalID: 470,
    types: ["Grass"],
  },
  {
    galarID: 203,
    name: "Glaceon",
    nationalID: 471,
    types: ["Ice"],
  },
  {
    galarID: 204,
    name: "Sylveon",
    nationalID: 700,
    types: ["Fairy"],
  },
  {
    galarID: 205,
    name: "Applin",
    nationalID: 840,
    types: ["Grass", "Dragon"],
  },
  {
    galarID: 206,
    name: "Flapple",
    nationalID: 841,
    types: ["Grass", "Dragon"],
  },
  {
    galarID: 207,
    name: "Appletun",
    nationalID: 842,
    types: ["Grass", "Dragon"],
  },
  {
    galarID: 208,
    name: "Espurr",
    nationalID: 677,
    types: ["Psychic"],
  },
  {
    galarID: 209,
    name: "Meowstic",
    nationalID: 678,
    types: ["Psychic"],
  },
  {
    galarID: 210,
    name: "Swirlix",
    nationalID: 684,
    types: ["Fairy"],
  },
  {
    galarID: 211,
    name: "Slurpuff",
    nationalID: 685,
    types: ["Fairy"],
  },
  {
    galarID: 212,
    name: "Spritzee",
    nationalID: 682,
    types: ["Fairy"],
  },
  {
    galarID: 213,
    name: "Aromatisse",
    nationalID: 683,
    types: ["Fairy"],
  },
  {
    galarID: 214,
    name: "Dewpider",
    nationalID: 751,
    types: ["Water", "Bug"],
  },
  {
    galarID: 215,
    name: "Araquanid",
    nationalID: 752,
    types: ["Water", "Bug"],
  },
  {
    galarID: 216,
    name: "Wynaut",
    nationalID: 360,
    types: ["Psychic"],
  },
  {
    galarID: 217,
    name: "Wobbuffet",
    nationalID: 202,
    types: ["Psychic"],
  },
  {
    galarID: 218,
    name: "Farfetch'd",
    nationalID: 83,
    types: ["Fighting"],
  },
  {
    galarID: 219,
    name: "Sirfetch'd",
    nationalID: 865,
    types: ["Fighting"],
  },
  {
    galarID: 220,
    name: "Chinchou",
    nationalID: 170,
    types: ["Water", "Electric"],
  },
  {
    galarID: 221,
    name: "Lanturn",
    nationalID: 171,
    types: ["Water", "Electric"],
  },
  {
    galarID: 222,
    name: "Croagunk",
    nationalID: 453,
    types: ["Poison", "Fighting"],
  },
  {
    galarID: 223,
    name: "Toxicroak",
    nationalID: 454,
    types: ["Poison", "Fighting"],
  },
  {
    galarID: 224,
    name: "Scraggy",
    nationalID: 559,
    types: ["Dark", "Fighting"],
  },
  {
    galarID: 225,
    name: "Scrafty",
    nationalID: 560,
    types: ["Dark", "Fighting"],
  },
  {
    galarID: 226,
    name: "Stunfisk",
    nationalID: 618,
    types: ["Ground", "Steel"],
  },
  {
    galarID: 227,
    name: "Shuckle",
    nationalID: 213,
    types: ["Bug", "Rock"],
  },
  {
    galarID: 228,
    name: "Barboach",
    nationalID: 339,
    types: ["Water", "Ground"],
  },
  {
    galarID: 229,
    name: "Whiscash",
    nationalID: 340,
    types: ["Water", "Ground"],
  },
  {
    galarID: 230,
    name: "Shellos",
    nationalID: 422,
    types: ["Water"],
  },
  {
    galarID: 231,
    name: "Gastrodon",
    nationalID: 423,
    types: ["Water", "Ground"],
  },
  {
    galarID: 232,
    name: "Wimpod",
    nationalID: 767,
    types: ["Bug", "Water"],
  },
  {
    galarID: 233,
    name: "Golisopod",
    nationalID: 768,
    types: ["Bug", "Water"],
  },
  {
    galarID: 234,
    name: "Binacle",
    nationalID: 688,
    types: ["Rock", "Water"],
  },
  {
    galarID: 235,
    name: "Barbaracle",
    nationalID: 689,
    types: ["Rock", "Water"],
  },
  {
    galarID: 236,
    name: "Corsola",
    nationalID: 222,
    types: ["Ghost"],
  },
  {
    galarID: 237,
    name: "Cursola",
    nationalID: 864,
    types: ["Ghost"],
  },
  {
    galarID: 238,
    name: "Impidimp",
    nationalID: 859,
    types: ["Dark", "Fairy"],
  },
  {
    galarID: 239,
    name: "Morgrem",
    nationalID: 860,
    types: ["Dark", "Fairy"],
  },
  {
    galarID: 240,
    name: "Grimmsnarl",
    nationalID: 861,
    types: ["Dark", "Fairy"],
  },
  {
    galarID: 241,
    name: "Hatenna",
    nationalID: 856,
    types: ["Psychic"],
  },
  {
    galarID: 242,
    name: "Hattrem",
    nationalID: 857,
    types: ["Psychic"],
  },
  {
    galarID: 243,
    name: "Hatterene",
    nationalID: 858,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 244,
    name: "Salandit",
    nationalID: 757,
    types: ["Poison", "Fire"],
  },
  {
    galarID: 245,
    name: "Salazzle",
    nationalID: 758,
    types: ["Poison", "Fire"],
  },
  {
    galarID: 246,
    name: "Pawniard",
    nationalID: 624,
    types: ["Dark", "Steel"],
  },
  {
    galarID: 247,
    name: "Bisharp",
    nationalID: 625,
    types: ["Dark", "Steel"],
  },
  {
    galarID: 248,
    name: "Throh",
    nationalID: 538,
    types: ["Fighting"],
  },
  {
    galarID: 249,
    name: "Sawk",
    nationalID: 539,
    types: ["Fighting"],
  },
  {
    galarID: 250,
    name: "Koffing",
    nationalID: 109,
    types: ["Poison"],
  },
  {
    galarID: 251,
    name: "Weezing",
    nationalID: 110,
    types: ["Poison", "Fairy"],
  },
  {
    galarID: 252,
    name: "Bonsly",
    nationalID: 438,
    types: ["Rock"],
  },
  {
    galarID: 253,
    name: "Sudowoodo",
    nationalID: 185,
    types: ["Rock"],
  },
  {
    galarID: 254,
    name: "Cleffa",
    nationalID: 173,
    types: ["Fairy"],
  },
  {
    galarID: 255,
    name: "Clefairy",
    nationalID: 35,
    types: ["Fairy"],
  },
  {
    galarID: 256,
    name: "Clefable",
    nationalID: 36,
    types: ["Fairy"],
  },
  {
    galarID: 257,
    name: "Togepi",
    nationalID: 175,
    types: ["Fairy"],
  },
  {
    galarID: 258,
    name: "Togetic",
    nationalID: 176,
    types: ["Fairy", "Flying"],
  },
  {
    galarID: 259,
    name: "Togekiss",
    nationalID: 468,
    types: ["Fairy", "Flying"],
  },
  {
    galarID: 260,
    name: "Munchlax",
    nationalID: 446,
    types: ["Normal"],
  },
  {
    galarID: 261,
    name: "Snorlax",
    nationalID: 143,
    types: ["Normal"],
  },
  {
    galarID: 262,
    name: "Cottonee",
    nationalID: 546,
    types: ["Grass", "Fairy"],
  },
  {
    galarID: 263,
    name: "Whimsicott",
    nationalID: 547,
    types: ["Grass", "Fairy"],
  },
  {
    galarID: 264,
    name: "Rhyhorn",
    nationalID: 111,
    types: ["Ground", "Rock"],
  },
  {
    galarID: 265,
    name: "Rhydon",
    nationalID: 112,
    types: ["Ground", "Rock"],
  },
  {
    galarID: 266,
    name: "Rhyperior",
    nationalID: 464,
    types: ["Ground", "Rock"],
  },
  {
    galarID: 267,
    name: "Gothita",
    nationalID: 574,
    types: ["Psychic"],
  },
  {
    galarID: 268,
    name: "Gothorita",
    nationalID: 575,
    types: ["Psychic"],
  },
  {
    galarID: 269,
    name: "Gothitelle",
    nationalID: 576,
    types: ["Psychic"],
  },
  {
    galarID: 270,
    name: "Solosis",
    nationalID: 577,
    types: ["Psychic"],
  },
  {
    galarID: 271,
    name: "Duosion",
    nationalID: 578,
    types: ["Psychic"],
  },
  {
    galarID: 272,
    name: "Reuniclus",
    nationalID: 579,
    types: ["Psychic"],
  },
  {
    galarID: 273,
    name: "Karrablast",
    nationalID: 588,
    types: ["Bug"],
  },
  {
    galarID: 274,
    name: "Escavalier",
    nationalID: 589,
    types: ["Bug", "Steel"],
  },
  {
    galarID: 275,
    name: "Shelmet",
    nationalID: 616,
    types: ["Bug"],
  },
  {
    galarID: 276,
    name: "Accelgor",
    nationalID: 617,
    types: ["Bug"],
  },
  {
    galarID: 277,
    name: "Elgyem",
    nationalID: 605,
    types: ["Psychic"],
  },
  {
    galarID: 278,
    name: "Beheeyem",
    nationalID: 606,
    types: ["Psychic"],
  },
  {
    galarID: 279,
    name: "Cubchoo",
    nationalID: 613,
    types: ["Ice"],
  },
  {
    galarID: 280,
    name: "Beartic",
    nationalID: 614,
    types: ["Ice"],
  },
  {
    galarID: 281,
    name: "Rufflet",
    nationalID: 627,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 282,
    name: "Braviary",
    nationalID: 628,
    types: ["Normal", "Flying"],
  },
  {
    galarID: 283,
    name: "Vullaby",
    nationalID: 629,
    types: ["Dark", "Flying"],
  },
  {
    galarID: 284,
    name: "Mandibuzz",
    nationalID: 630,
    types: ["Dark", "Flying"],
  },
  {
    galarID: 285,
    name: "Skorupi",
    nationalID: 451,
    types: ["Poison", "Bug"],
  },
  {
    galarID: 286,
    name: "Drapion",
    nationalID: 452,
    types: ["Poison", "Dark"],
  },
  {
    galarID: 287,
    name: "Litwick",
    nationalID: 607,
    types: ["Ghost", "Fire"],
  },
  {
    galarID: 288,
    name: "Lampent",
    nationalID: 608,
    types: ["Ghost", "Fire"],
  },
  {
    galarID: 289,
    name: "Chandelure",
    nationalID: 609,
    types: ["Ghost", "Fire"],
  },
  {
    galarID: 290,
    name: "Inkay",
    nationalID: 686,
    types: ["Dark", "Psychic"],
  },
  {
    galarID: 291,
    name: "Malamar",
    nationalID: 687,
    types: ["Dark", "Psychic"],
  },
  {
    galarID: 292,
    name: "Sneasel",
    nationalID: 215,
    types: ["Dark", "Ice"],
  },
  {
    galarID: 293,
    name: "Weavile",
    nationalID: 461,
    types: ["Dark", "Ice"],
  },
  {
    galarID: 294,
    name: "Sableye",
    nationalID: 302,
    types: ["Dark", "Ghost"],
  },
  {
    galarID: 295,
    name: "Mawile",
    nationalID: 303,
    types: ["Steel", "Fairy"],
  },
  {
    galarID: 296,
    name: "Maractus",
    nationalID: 556,
    types: ["Grass"],
  },
  {
    galarID: 297,
    name: "Sigilyph",
    nationalID: 561,
    types: ["Psychic", "Flying"],
  },
  {
    galarID: 298,
    name: "Riolu",
    nationalID: 447,
    types: ["Fighting"],
  },
  {
    galarID: 299,
    name: "Lucario",
    nationalID: 448,
    types: ["Fighting", "Steel"],
  },
  {
    galarID: 300,
    name: "Torkoal",
    nationalID: 324,
    types: ["Fire"],
  },
  {
    galarID: 301,
    name: "Mimikyu",
    nationalID: 778,
    types: ["Ghost", "Fairy"],
  },
  {
    galarID: 302,
    name: "Cufant",
    nationalID: 878,
    types: ["Steel"],
  },
  {
    galarID: 303,
    name: "Copperajah",
    nationalID: 879,
    types: ["Steel"],
  },
  {
    galarID: 304,
    name: "Qwilfish",
    nationalID: 211,
    types: ["Water", "Poison"],
  },
  {
    galarID: 305,
    name: "Frillish",
    nationalID: 592,
    types: ["Water", "Ghost"],
  },
  {
    galarID: 306,
    name: "Jellicent",
    nationalID: 593,
    types: ["Water", "Ghost"],
  },
  {
    galarID: 307,
    name: "Mareanie",
    nationalID: 747,
    types: ["Poison", "Water"],
  },
  {
    galarID: 308,
    name: "Toxapex",
    nationalID: 748,
    types: ["Poison", "Water"],
  },
  {
    galarID: 309,
    name: "Cramorant",
    nationalID: 845,
    types: ["Flying", "Water"],
  },
  {
    galarID: 310,
    name: "Toxel",
    nationalID: 848,
    types: ["Electric", "Poison"],
  },
  {
    galarID: 311,
    name: "Toxtricity",
    nationalID: 849,
    types: ["Electric", "Poison"],
  },
  {
    galarID: 312,
    name: "Silicobra",
    nationalID: 843,
    types: ["Ground"],
  },
  {
    galarID: 313,
    name: "Sandaconda",
    nationalID: 844,
    types: ["Ground"],
  },
  {
    galarID: 314,
    name: "Hippopotas",
    nationalID: 449,
    types: ["Ground"],
  },
  {
    galarID: 315,
    name: "Hippowdon",
    nationalID: 450,
    types: ["Ground"],
  },
  {
    galarID: 316,
    name: "Durant",
    nationalID: 632,
    types: ["Bug", "Steel"],
  },
  {
    galarID: 317,
    name: "Heatmor",
    nationalID: 631,
    types: ["Fire"],
  },
  {
    galarID: 318,
    name: "Helioptile",
    nationalID: 694,
    types: ["Electric", "Normal"],
  },
  {
    galarID: 319,
    name: "Heliolisk",
    nationalID: 695,
    types: ["Electric", "Normal"],
  },
  {
    galarID: 320,
    name: "Hawlucha",
    nationalID: 701,
    types: ["Fighting", "Flying"],
  },
  {
    galarID: 321,
    name: "Trapinch",
    nationalID: 328,
    types: ["Ground"],
  },
  {
    galarID: 322,
    name: "Vibrava",
    nationalID: 329,
    types: ["Ground", "Dragon"],
  },
  {
    galarID: 323,
    name: "Flygon",
    nationalID: 330,
    types: ["Ground", "Dragon"],
  },
  {
    galarID: 324,
    name: "Axew",
    nationalID: 610,
    types: ["Dragon"],
  },
  {
    galarID: 325,
    name: "Fraxure",
    nationalID: 611,
    types: ["Dragon"],
  },
  {
    galarID: 326,
    name: "Haxorus",
    nationalID: 612,
    types: ["Dragon"],
  },
  {
    galarID: 327,
    name: "Yamask",
    nationalID: 562,
    types: ["Ground", "Ghost"],
  },
  {
    galarID: 328,
    name: "Runerigus",
    nationalID: 867,
    types: ["Ground", "Ghost"],
  },
  {
    galarID: 329,
    name: "Cofagrigus",
    nationalID: 563,
    types: ["Ghost"],
  },
  {
    galarID: 330,
    name: "Honedge",
    nationalID: 679,
    types: ["Steel", "Ghost"],
  },
  {
    galarID: 331,
    name: "Doublade",
    nationalID: 680,
    types: ["Steel", "Ghost"],
  },
  {
    galarID: 332,
    name: "Aegislash",
    nationalID: 681,
    types: ["Steel", "Ghost"],
  },
  {
    galarID: 333,
    name: "Ponyta",
    nationalID: 77,
    types: ["Psychic"],
  },
  {
    galarID: 334,
    name: "Rapidash",
    nationalID: 78,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 335,
    name: "Sinistea",
    nationalID: 854,
    types: ["Ghost"],
  },
  {
    galarID: 336,
    name: "Polteageist",
    nationalID: 855,
    types: ["Ghost"],
  },
  {
    galarID: 337,
    name: "Indeedee",
    nationalID: 876,
    types: ["Psychic", "Normal"],
  },
  {
    galarID: 338,
    name: "Phantump",
    nationalID: 708,
    types: ["Ghost", "Grass"],
  },
  {
    galarID: 339,
    name: "Trevenant",
    nationalID: 709,
    types: ["Ghost", "Grass"],
  },
  {
    galarID: 340,
    name: "Morelull",
    nationalID: 755,
    types: ["Grass", "Fairy"],
  },
  {
    galarID: 341,
    name: "Shiinotic",
    nationalID: 756,
    types: ["Grass", "Fairy"],
  },
  {
    galarID: 342,
    name: "Oranguru",
    nationalID: 765,
    types: ["Normal", "Psychic"],
  },
  {
    galarID: 343,
    name: "Passimian",
    nationalID: 766,
    types: ["Fighting"],
  },
  {
    galarID: 344,
    name: "Morpeko",
    nationalID: 877,
    types: ["Electric", "Dark"],
  },
  {
    galarID: 345,
    name: "Falinks",
    nationalID: 870,
    types: ["Fighting"],
  },
  {
    galarID: 346,
    name: "Drampa",
    nationalID: 780,
    types: ["Normal", "Dragon"],
  },
  {
    galarID: 347,
    name: "Turtonator",
    nationalID: 776,
    types: ["Fire", "Dragon"],
  },
  {
    galarID: 348,
    name: "Togedemaru",
    nationalID: 777,
    types: ["Electric", "Steel"],
  },
  {
    galarID: 349,
    name: "Snom",
    nationalID: 872,
    types: ["Ice", "Bug"],
  },
  {
    galarID: 350,
    name: "Frosmoth",
    nationalID: 873,
    types: ["Ice", "Bug"],
  },
  {
    galarID: 351,
    name: "Clobbopus",
    nationalID: 852,
    types: ["Fighting"],
  },
  {
    galarID: 352,
    name: "Grapploct",
    nationalID: 853,
    types: ["Fighting"],
  },
  {
    galarID: 353,
    name: "Pincurchin",
    nationalID: 871,
    types: ["Electric"],
  },
  {
    galarID: 354,
    name: "Mantyke",
    nationalID: 458,
    types: ["Water", "Flying"],
  },
  {
    galarID: 355,
    name: "Mantine",
    nationalID: 226,
    types: ["Water", "Flying"],
  },
  {
    galarID: 356,
    name: "Wailmer",
    nationalID: 320,
    types: ["Water"],
  },
  {
    galarID: 357,
    name: "Wailord",
    nationalID: 321,
    types: ["Water"],
  },
  {
    galarID: 358,
    name: "Bergmite",
    nationalID: 712,
    types: ["Ice"],
  },
  {
    galarID: 359,
    name: "Avalugg",
    nationalID: 713,
    types: ["Ice"],
  },
  {
    galarID: 360,
    name: "Dhelmise",
    nationalID: 781,
    types: ["Ghost", "Grass"],
  },
  {
    galarID: 361,
    name: "Lapras",
    nationalID: 131,
    types: ["Water", "Ice"],
  },
  {
    galarID: 362,
    name: "Lunatone",
    nationalID: 337,
    types: ["Rock", "Psychic"],
  },
  {
    galarID: 363,
    name: "Solrock",
    nationalID: 338,
    types: ["Rock", "Psychic"],
  },
  {
    galarID: 364,
    name: "Mime Jr.",
    nationalID: 439,
    types: ["Psychic", "Fairy"],
  },
  {
    galarID: 365,
    name: "Mr. Mime",
    nationalID: 122,
    types: ["Ice", "Psychic"],
  },
  {
    galarID: 366,
    name: "Mr. Rime",
    nationalID: 866,
    types: ["Ice", "Psychic"],
  },
  {
    galarID: 367,
    name: "Darumaka",
    nationalID: 554,
    types: ["Ice"],
  },
  {
    galarID: 368,
    name: "Darmanitan",
    nationalID: 555,
    types: ["Ice"],
  },
  {
    galarID: 369,
    name: "Stonjourner",
    nationalID: 874,
    types: ["Rock"],
  },
  {
    galarID: 370,
    name: "Eiscue",
    nationalID: 875,
    types: ["Ice"],
  },
  {
    galarID: 371,
    name: "Duraludon",
    nationalID: 884,
    types: ["Steel", "Dragon"],
  },
  {
    galarID: 372,
    name: "Rotom",
    nationalID: 479,
    types: ["Electric", "Ghost"],
  },
  {
    galarID: 373,
    name: "Ditto",
    nationalID: 132,
    types: ["Normal"],
  },
  {
    galarID: 374,
    name: "Dracozolt",
    nationalID: 880,
    types: ["Electric", "Dragon"],
  },
  {
    galarID: 375,
    name: "Arctozolt",
    nationalID: 881,
    types: ["Electric", "Ice"],
  },
  {
    galarID: 376,
    name: "Dracovish",
    nationalID: 882,
    types: ["Water", "Dragon"],
  },
  {
    galarID: 377,
    name: "Arctovish",
    nationalID: 883,
    types: ["Water", "Ice"],
  },
  {
    galarID: 378,
    name: "Charmander",
    nationalID: 4,
    types: ["Fire"],
  },
  {
    galarID: 379,
    name: "Charmeleon",
    nationalID: 5,
    types: ["Fire"],
  },
  {
    galarID: 380,
    name: "Charizard",
    nationalID: 6,
    types: ["Fire", "Flying"],
  },
  {
    galarID: 381,
    name: "Type: Null",
    nationalID: 772,
    types: ["Normal"],
  },
  {
    galarID: 382,
    name: "Silvally",
    nationalID: 773,
    types: ["Normal"],
  },
  {
    galarID: 383,
    name: "Larvitar",
    nationalID: 246,
    types: ["Rock", "Ground"],
  },
  {
    galarID: 384,
    name: "Pupitar",
    nationalID: 247,
    types: ["Rock", "Ground"],
  },
  {
    galarID: 385,
    name: "Tyranitar",
    nationalID: 248,
    types: ["Rock", "Dark"],
  },
  {
    galarID: 386,
    name: "Deino",
    nationalID: 633,
    types: ["Dark", "Dragon"],
  },
  {
    galarID: 387,
    name: "Zweilous",
    nationalID: 634,
    types: ["Dark", "Dragon"],
  },
  {
    galarID: 388,
    name: "Hydreigon",
    nationalID: 635,
    types: ["Dark", "Dragon"],
  },
  {
    galarID: 389,
    name: "Goomy",
    nationalID: 704,
    types: ["Dragon"],
  },
  {
    galarID: 390,
    name: "Sliggoo",
    nationalID: 705,
    types: ["Dragon"],
  },
  {
    galarID: 391,
    name: "Goodra",
    nationalID: 706,
    types: ["Dragon"],
  },
  {
    galarID: 392,
    name: "Jangmo-o",
    nationalID: 782,
    types: ["Dragon"],
  },
  {
    galarID: 393,
    name: "Hakamo-o",
    nationalID: 783,
    types: ["Dragon", "Fighting"],
  },
  {
    galarID: 394,
    name: "Kommo-o",
    nationalID: 784,
    types: ["Dragon", "Fighting"],
  },
  {
    galarID: 395,
    name: "Dreepy",
    nationalID: 885,
    types: ["Dragon", "Ghost"],
  },
  {
    galarID: 396,
    name: "Drakloak",
    nationalID: 886,
    types: ["Dragon", "Ghost"],
  },
  {
    galarID: 397,
    name: "Dragapult",
    nationalID: 887,
    types: ["Dragon", "Ghost"],
  },
  {
    galarID: 398,
    name: "Zacian",
    nationalID: 888,
    types: ["Fairy"],
  },
  {
    galarID: 399,
    name: "Zamazenta",
    nationalID: 889,
    types: ["Fighting"],
  },
  {
    galarID: 400,
    name: "Eternatus",
    nationalID: 890,
    types: ["Poison", "Dragon"],
  },
];

export default galarPokedex;
